// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.7
// source: proto/brr.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg       string  `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	ClientId  int32   `protobuf:"varint,2,opt,name=clientId,proto3" json:"clientId,omitempty"`
	Timestamp []int32 `protobuf:"varint,3,rep,packed,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_brr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_proto_brr_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ChatMessage) GetClientId() int32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *ChatMessage) GetTimestamp() []int32 {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ServerReponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp []int32 `protobuf:"varint,1,rep,packed,name=timestamp,proto3" json:"timestamp,omitempty"`
	Msg       string  `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ServerReponse) Reset() {
	*x = ServerReponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_brr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerReponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerReponse) ProtoMessage() {}

func (x *ServerReponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerReponse.ProtoReflect.Descriptor instead.
func (*ServerReponse) Descriptor() ([]byte, []int) {
	return file_proto_brr_proto_rawDescGZIP(), []int{1}
}

func (x *ServerReponse) GetTimestamp() []int32 {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ServerReponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ServerWelcome struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VClock []int32 `protobuf:"varint,1,rep,packed,name=vClock,proto3" json:"vClock,omitempty"`
	Id     int32   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ServerWelcome) Reset() {
	*x = ServerWelcome{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_brr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerWelcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerWelcome) ProtoMessage() {}

func (x *ServerWelcome) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerWelcome.ProtoReflect.Descriptor instead.
func (*ServerWelcome) Descriptor() ([]byte, []int) {
	return file_proto_brr_proto_rawDescGZIP(), []int{2}
}

func (x *ServerWelcome) GetVClock() []int32 {
	if x != nil {
		return x.VClock
	}
	return nil
}

func (x *ServerWelcome) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ClientJoin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientName string `protobuf:"bytes,1,opt,name=clientName,proto3" json:"clientName,omitempty"`
}

func (x *ClientJoin) Reset() {
	*x = ClientJoin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_brr_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientJoin) ProtoMessage() {}

func (x *ClientJoin) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brr_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientJoin.ProtoReflect.Descriptor instead.
func (*ClientJoin) Descriptor() ([]byte, []int) {
	return file_proto_brr_proto_rawDescGZIP(), []int{3}
}

func (x *ClientJoin) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

type ClientLeave struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId   int32   `protobuf:"varint,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	Timestamp  []int32 `protobuf:"varint,2,rep,packed,name=timestamp,proto3" json:"timestamp,omitempty"`
	ClientName string  `protobuf:"bytes,3,opt,name=clientName,proto3" json:"clientName,omitempty"`
}

func (x *ClientLeave) Reset() {
	*x = ClientLeave{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_brr_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientLeave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientLeave) ProtoMessage() {}

func (x *ClientLeave) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brr_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientLeave.ProtoReflect.Descriptor instead.
func (*ClientLeave) Descriptor() ([]byte, []int) {
	return file_proto_brr_proto_rawDescGZIP(), []int{4}
}

func (x *ClientLeave) GetClientId() int32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *ClientLeave) GetTimestamp() []int32 {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ClientLeave) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

type ServerBye struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ServerBye) Reset() {
	*x = ServerBye{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_brr_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerBye) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerBye) ProtoMessage() {}

func (x *ServerBye) ProtoReflect() protoreflect.Message {
	mi := &file_proto_brr_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerBye.ProtoReflect.Descriptor instead.
func (*ServerBye) Descriptor() ([]byte, []int) {
	return file_proto_brr_proto_rawDescGZIP(), []int{5}
}

func (x *ServerBye) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_proto_brr_proto protoreflect.FileDescriptor

var file_proto_brr_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x72, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x07, 0x67, 0x72, 0x70, 0x63, 0x42, 0x72, 0x72, 0x22, 0x59, 0x0a, 0x0b, 0x43, 0x68,
	0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x3f, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52,
	0x65, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x37, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x43, 0x6c, 0x6f, 0x63,
	0x6b, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x76, 0x43, 0x6c, 0x6f, 0x63, 0x6b, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x2c, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x1e, 0x0a,
	0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x67, 0x0a,
	0x0b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x1d, 0x0a, 0x09, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x42, 0x79, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0xbd, 0x01, 0x0a, 0x0a, 0x43, 0x68, 0x69, 0x74, 0x74, 0x79,
	0x43, 0x68, 0x61, 0x74, 0x12, 0x37, 0x0a, 0x08, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d,
	0x12, 0x13, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x42, 0x72, 0x72, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x1a, 0x16, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x42, 0x72, 0x72, 0x2e,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x12, 0x3f, 0x0a,
	0x0b, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x42, 0x72, 0x72, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x1a, 0x16, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x42, 0x72, 0x72, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x12, 0x35,
	0x0a, 0x09, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x14, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x42, 0x72, 0x72, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4c, 0x65, 0x61, 0x76,
	0x65, 0x1a, 0x12, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x42, 0x72, 0x72, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x42, 0x79, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_brr_proto_rawDescOnce sync.Once
	file_proto_brr_proto_rawDescData = file_proto_brr_proto_rawDesc
)

func file_proto_brr_proto_rawDescGZIP() []byte {
	file_proto_brr_proto_rawDescOnce.Do(func() {
		file_proto_brr_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_brr_proto_rawDescData)
	})
	return file_proto_brr_proto_rawDescData
}

var file_proto_brr_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_brr_proto_goTypes = []interface{}{
	(*ChatMessage)(nil),   // 0: grpcBrr.ChatMessage
	(*ServerReponse)(nil), // 1: grpcBrr.ServerReponse
	(*ServerWelcome)(nil), // 2: grpcBrr.ServerWelcome
	(*ClientJoin)(nil),    // 3: grpcBrr.ClientJoin
	(*ClientLeave)(nil),   // 4: grpcBrr.ClientLeave
	(*ServerBye)(nil),     // 5: grpcBrr.ServerBye
}
var file_proto_brr_proto_depIdxs = []int32{
	3, // 0: grpcBrr.ChittyChat.JoinRoom:input_type -> grpcBrr.ClientJoin
	0, // 1: grpcBrr.ChittyChat.SendMessage:input_type -> grpcBrr.ChatMessage
	4, // 2: grpcBrr.ChittyChat.LeaveRoom:input_type -> grpcBrr.ClientLeave
	2, // 3: grpcBrr.ChittyChat.JoinRoom:output_type -> grpcBrr.ServerWelcome
	1, // 4: grpcBrr.ChittyChat.SendMessage:output_type -> grpcBrr.ServerReponse
	5, // 5: grpcBrr.ChittyChat.LeaveRoom:output_type -> grpcBrr.ServerBye
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_brr_proto_init() }
func file_proto_brr_proto_init() {
	if File_proto_brr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_brr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_brr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerReponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_brr_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerWelcome); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_brr_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientJoin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_brr_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientLeave); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_brr_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerBye); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_brr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_brr_proto_goTypes,
		DependencyIndexes: file_proto_brr_proto_depIdxs,
		MessageInfos:      file_proto_brr_proto_msgTypes,
	}.Build()
	File_proto_brr_proto = out.File
	file_proto_brr_proto_rawDesc = nil
	file_proto_brr_proto_goTypes = nil
	file_proto_brr_proto_depIdxs = nil
}
